export type User = { id: string; email: string; name: string; avatarUrl: string; accessStatus?: string; accessNote?: string };
export type ProjectRepository = { id: string; role: string; sourceRepoUrl?: string; provider?: string; serviceNames?: string[]; createdAt?: string };
export type ProjectService = { id: string; name: string; url: string; type?: string; visibility?: string; authRequired?: boolean; createdAt?: string };
export type Project = { id: string; title: string; previewUrl?: string; selectedServiceName?: string; repositories?: ProjectRepository[]; services?: ProjectService[]; status: string; errorMessage?: string; createdAt: string; updatedAt: string };
export type MessageQuota = { used: number; limit: number; remaining: number; paidRemaining?: number; lifetimeUsed?: number; resetsAt?: string };
export type ProjectQuota = { used: number; limit: number; remaining: number; baseLimit: number; paidSlots: number; nextExpiresAt?: string };
export type UserNotice = { id: string; userId?: string; sender: 'admin' | 'system' | 'user'; severity: string; body: string; readAt?: string; dismissedAt?: string; unsentAt?: string; createdAt: string };
export type ProjectArchive = { id: string; projectId: string; projectTitle: string; downloadUrl?: string; githubRepoUrl?: string; status: string; error?: string; expiresAt: string; createdAt: string };
export type Me = { user: User | null; isAdmin?: boolean; githubConnected?: boolean; githubNeedsReconnect?: boolean; messageQuota?: MessageQuota; projectQuota?: ProjectQuota; notices?: UserNotice[]; auth?: { googleConfigured: boolean; devAuth: boolean } };
export type Feed = { project: Project; localMessages: Message[]; messages: AgentMessage[]; activity: AgentActivity[]; live?: ConversationLiveState | null; warning?: string };
export type PreviewStatus = { ready: boolean; maintenance?: boolean; status?: string; checkedAt?: string };
export type MessageAttachment = { id: string; filename: string; contentType?: string; size?: number; url?: string };
export type Message = { id: string; role: string; body: string; attachments?: MessageAttachment[]; createdAt: string };
export type AgentMessage = { id?: string; role?: string; body?: string; content?: string; created_at?: string };
export type AgentActivity = { id?: string; activity_type?: string; type?: string; message?: string; status?: string; occurred_at?: string };
export type ConversationLiveState = { conversationId?: string; isProcessing?: boolean; streamText?: string; startedAt?: string; queuedTurns?: number };
export type BuilderMode = 'overlay' | 'split';
export type BusyPolicy = 'queue' | 'steer';
export type ProjectListResponse = { projects: Project[] | null; projectCap?: number; projectQuota?: ProjectQuota };
export type ProjectExportResponse = { githubRepoUrl: string; jobId: string };
export type ProjectArchiveResponse = { archive: ProjectArchive; downloadUrl: string };
export type UserFeedRow = { kind: 'user'; id: string; role: 'user'; body: string; attachments: MessageAttachment[]; time?: string };
export type NotificationFeedRow = { kind: 'notification'; id: string; body: string; time?: string; active?: boolean; fallback?: boolean };
export type FeedRow = UserFeedRow | NotificationFeedRow;
export type PendingAttachment = { id: string; file: File };
export type AdminConfigEntry = { value: string; secret: boolean; set: boolean };
export type AdminConfigResponse = { config: Record<string, AdminConfigEntry>; adminEmail: string };
export type PoolRow = { id: string; label: string; agentId: string; serverId: string };
export type AdminUserSummary = {
  user: User;
  projectCount: number;
  projectLimit?: number;
  paidProjectSlots?: number;
  projectSlotsExpire?: string;
  messageCount: number;
  dailyMessageCount: number;
  freeMessageLimit: number;
  paidCreditBalance: number;
  githubConnected: boolean;
  subscriptionStatus: string;
  paidTotalCents: number;
  paidCurrency: string;
  lastMessageAt?: string;
  lastProjectAt?: string;
  latestNotice?: UserNotice;
};
export type AdminProjectSummary = { project: Project; messageCount: number };
export type AdminUserDetail = { summary: AdminUserSummary; projects: AdminProjectSummary[]; notices: UserNotice[] };
export type AdminUsersResponse = { users: AdminUserSummary[]; pagination: { page: number; perPage: number; total: number } };
export type AppDialogConfig = {
  title: string;
  body: string;
  tone?: 'info' | 'warning' | 'danger';
  confirmLabel?: string;
  cancelLabel?: string;
  onConfirm?: () => void | Promise<void>;
};
